export type UserRegisterInfoItem = {
  id: string,
  nickName: string,
  realName: string,
  studentNumber: string,
  gender: number,
  userType: number,
  phoneNumber: string,
  faculty: number,
  identified: number,
  material: string,
  isComplete: number,
  activityList: number[],
  country: string,
  province: string,
  city: string,
}
