export type UserGeneralInfoItem = {
  id: number,
  nickname: string,
  realname: string,
  studentNumber: string,
  gender: number,
  userType: number,
  phoneNumber: string,
  faculty: number,
  identified: number,
  material: string,
  activityList: number[],
  isBlack: number,
  isComplete: number,
}
